unique_ids:
  forms:
    ClientTestComponent: FYFOVRKKG2KTASYPJ4GIAF2CMW6UITOT
    ClientTestComponent.ModuleTemplate: FKY5FNRSNA34SFPDPG77EKOZN6OSABLU
    ClientTestComponent.ModuleTemplate.ClassTemplate: GNNTIIDYMT5FWE3ZTN4UVAQPZL3CBGDI
    ClientTestComponent.ModuleTemplate.ClassTemplate.MethodTemplate: 4AW6PCB47JKSVGMMWNMMQTFYEHZZK2AB
    UnitTestTemplate: '1692215698898603425854417.3401'
    Form1: EUQNMYVIAPU3IQQNXIQOPUF7YXOXGWFS
  modules:
    kompot._builtins: OMVA45D2AFWO74HYJNH5VGQQB6FGA4A2
    service_worker: BFDAX7334EVD2UITLENI63GMFYLVI4OT
    fido: UMUNTXF4C3LFOPPSGUEDCTTDWOS7JOFN
    dataklasses: G474VTPQWVC6RWA6X5SMDFPI2H3SGAZH
    pedantic: 42MPRKQNRL5DPWNRMK7NPYQMAQ7LX7IQ
    kompot._serialize: WE3KHPSZMPTDDLWSQR77GMHHCBLPMC66
    atomic.rendering: UJN3DNDU5VXUN5MLNNA7AO47HP2SPR7C
    non_blocking: TDXZCQRMVW2DDPGL65Q4SEV52MPCTHA6
    kompot._rpc: 42WZHNG4TEWT2CXERRMVPZNO5M655UH7
    atomic.contexts: ZDZBENQV4UMOX6M43ZVYBUSAC3MR7W3J
    web_worker: JXEX6PW2T36XS7RMVADHUHXU6CRXM3VN
    atomic.helpers: GVUNMVSI2UAIRDCG5EWPSCHA2CG3NO3I
    atomic.subscribers: A2WMN2PSQUUTLZDLNISVKVYUI2R7TC6E
    kompot._register: EC42H5KYDA5FV42S2CF4ILNLN5ZRZYYI
    atomic.registrar: 3TWTOC4JZCMQM4MJN65RSLG2CDSS3FWX
    atomic.decorators: CFOJVHV6ETEJM56KWSQHCYKDHBTNXNSV
    cluegen: BVZBHASZZIPYSTH3Z7LWUZB6I3Z47NIR
    atomic.constants: 4AXLVS2TLMB7SA6SKHLHUYV74ZW4FPXP
    atomic.utils: 4SA7HDPARZAY7ZZ75WUO4LHL7ZIGGPC4
    atomic: OXQAUIAMC5ZYCUOMNYRLK66MGBPVNE35
    atomic.atoms: G7K5XMC6CPCQYNAJNPYK6UVLAYCAZSCL
    client_unittest: NLVHFFFHA6TNIHSPPFUJGEA4GUFD4GLO
    exceptions: 2USBDTR7TNNBSUAGHB2HLEBWRLUDPZFM
    kompot: YPYHWLPYXRJVFC45T4QJVZYWBAOTFXGA
    kompot._batcher: NA5PIIDFNECL2FSDJSUDH3EX5NUBYJB6
  server_modules:
    fido_webauthn: Z6P45WTCUU27BMDOU336ZTDMG5EASV5W
    web_worker_endpoint: 4LOVTWLSZCE2V6UJFKG5CMDN7GQW3TR3
  assets:
    standard-page.html: 7WXQKFRCH5SZXEWU75SNL2ATQS7YEAJ4
    theme.css: NVBHO4JFHOY22SMG5YEBSY67OCDKEWAT
    anvil_labs/client_sw.js: OMXRFZKMTYDSNGYKSBKQKCA6ZAZJGQ27
    anvil_labs/sw.js: FUPNLWJE4V73SXK6INPRGTLH3JJALRBG
